### ISSUE TITLE
Add linter/formatter GitHub action

### ISSUE THREAD

**Issue by andrewmcodes** [JuanCrg90/vpr#12]
I noticed you aren’t using a linter/formatter like rubocop or standardRB. Would you be interested in adding one? 

If so I can hook up a GitHub action for you. Check out [this repo](https://github.com/hopsoft/stimulus_reflex) for an example of actions I have created.

**Comment by JuanCrg90** [comment]
Hi @andrewmcodes, I'd be great if you could add standardrb to the project 😄
