### ISSUE TITLE
Allow to use vpr even if you are not in the root directory

### ISSUE THREAD

**Issue by JuanCrg90** [JuanCrg90/vpr#17]
Currently vpr only can be used in the project root directory where `.git` directory lives.

```
Traceback (most recent call last):
/Users/juancarlosruiz/project/app/models/.git: path does not exist (ArgumentError)
```

Update the behavior to look for `.git` directory in the parent directories

**Comment by schmidt** [comment]
Fix suggested in https://github.com/JuanCrg90/vpr/pull/23
