### ISSUE TITLE
Add support vpr branch in bitbucket

### ISSUE THREAD

**Issue by JuanCrg90** [JuanCrg90/vpr#18]
The route for branches in bitbucket is different to the GitHub endpoint

update
```
vpr branch
```

to support bitbucket 

examples:

GitHub:
`https://github.com/JuanCrg90/vpr/tree/master`

bitbucket
`https://bitbucket.org/JuanCrg90/vpr/branch/master`

**Comment by n8chz** [comment]
Should this open the code page of the current branch in Bitbucket, as in Github?

An example would be:
https://bitbucket.org/n8chz/phaxeer/src/1ca2307a8974e2df35095f102ec1d1c4dd239959/?at=master

A simpler URL that is one click away from the above:
https://bitbucket.org/n8chz/phaxeer/branch/master

**Comment by JuanCrg90** [comment]
@n8chz the URL should be

`https://bitbucket.org/<USERNAME>/<PROJECT>/branch/<YOUR_BRANCH>`

for example
https://bitbucket.org/n8chz/phaxeer/branch/dev send you to your dev branch

`tree/master` changes to `branch/master`
